using Microsoft.Data.Sqlite;
using PanoramaBridge.Core.Storage;

namespace PanoramaBridge.Tests.Storage;

/// <summary>
/// Widening the ledger's primary key to the file <em>and</em> its destination.
/// </summary>
/// <remarks>
/// <para>
/// Every migration before this one was a single <c>ALTER TABLE ADD COLUMN</c>. SQLite cannot
/// alter a primary key, so this one rebuilds the table -- and the table is the record of what has
/// already been uploaded. Lose it and every instrument re-sends everything it has; half-apply it
/// and files are reported verified that are not.
/// </para>
/// <para>
/// So these tests are about the data surviving, not about the schema being pretty. The one that
/// matters most is the first: a ledger written by the shipped release opens, migrates, and still
/// says "settled" about the rows it settled, because the alternative is three hundred gigabytes
/// going back over the network the morning after an update.
/// </para>
/// </remarks>
public sealed class LedgerRekeyMigrationTests : IDisposable
{
    private readonly string _directory =
        Directory.CreateTempSubdirectory("pb-rekey-").FullName;

    private string LedgerPath => Path.Combine(_directory, "state.db");

    /// <summary>
    /// Builds a ledger in the shape v26.8.1 wrote: schema 5, keyed by local path alone.
    /// </summary>
    /// <remarks>
    /// Written as raw SQL rather than by an older build, because the point is to reproduce the
    /// shape exactly. A fixture generated by the current code would be migrated already and would
    /// prove nothing.
    /// </remarks>
    private void WriteLegacyLedger(params (string Local, string Remote, int State)[] rows)
    {
        using var connection = new SqliteConnection($"Data Source={LedgerPath}");
        connection.Open();

        using var command = connection.CreateCommand();
        command.CommandText =
            """
            CREATE TABLE uploads (
              local_path    TEXT    PRIMARY KEY COLLATE NOCASE,
              remote_path   TEXT    NOT NULL,
              size          INTEGER NOT NULL,
              mtime_utc     INTEGER NOT NULL,
              md5           TEXT,
              sha256        TEXT,
              state         INTEGER NOT NULL,
              verify_method INTEGER NOT NULL DEFAULT 0,
              verified_utc  INTEGER,
              attempts      INTEGER NOT NULL DEFAULT 0,
              last_error    TEXT,
              is_dataset    INTEGER NOT NULL DEFAULT 0,
              raw_check     TEXT,
              resolution    INTEGER NOT NULL DEFAULT 0,
              rename_to     TEXT,
              conflict_kind INTEGER NOT NULL DEFAULT 0
            );

            CREATE TABLE hash_cache (
              local_path TEXT    NOT NULL COLLATE NOCASE,
              size       INTEGER NOT NULL,
              mtime_utc  INTEGER NOT NULL,
              md5        TEXT,
              sha256     TEXT,
              PRIMARY KEY (local_path, size, mtime_utc)
            );

            CREATE TABLE schema_version (version INTEGER NOT NULL);
            INSERT INTO schema_version (version) VALUES (5);
            """;
        command.ExecuteNonQuery();

        foreach (var (local, remote, state) in rows)
        {
            command.Parameters.Clear();
            command.CommandText =
                """
                INSERT INTO uploads
                  (local_path, remote_path, size, mtime_utc, md5, sha256, state,
                   verify_method, verified_utc, attempts)
                VALUES ($local, $remote, 4096, 1700000000000, $md5, NULL, $state, $verify, 1700000001000, 1);
                """;
            command.Parameters.AddWithValue("$local", local);
            command.Parameters.AddWithValue("$remote", remote);
            command.Parameters.AddWithValue("$state", state);
            command.Parameters.AddWithValue("$md5", "d41d8cd98f00b204e9800998ecf8427e");

            // ServerMd5, written as the number the column holds. Spelled out because a bare 1
            // here silently means SizeOnly, and a fixture claiming a weaker check than it means
            // would let a migration that downgraded verification pass unnoticed.
            command.Parameters.AddWithValue("$verify", (int)VerifyMethod.ServerMd5);
            command.ExecuteNonQuery();
        }

        SqliteConnection.ClearAllPools();
    }

    [Fact]
    public async Task A_ledger_from_the_shipped_release_still_says_settled_after_migrating()
    {
        // The one that matters. A verified row has to stay verified across the rebuild, at the
        // destination it was verified to -- otherwise the first sweep after an update re-uploads
        // an entire instrument's history.
        WriteLegacyLedger(
            (@"D:\Data\run1.raw", "/_webdav/MacCoss/QC/@files/run1.raw", (int)TransferState.Verified),
            (@"D:\Data\run2.raw", "/_webdav/MacCoss/QC/@files/run2.raw", (int)TransferState.Verified));

        await using var store = new SqliteStateStore(LedgerPath);

        var row = await store.GetAsync(
            new LedgerKey(@"D:\Data\run1.raw", "/_webdav/MacCoss/QC/@files/run1.raw"));

        row.ShouldNotBeNull();
        row.State.ShouldBe(TransferState.Verified);
        row.VerifyMethod.ShouldBe(VerifyMethod.ServerMd5);
        row.VerifiedUtc.ShouldNotBeNull();

        var stamp = new LocalFileStamp(@"D:\Data\run1.raw", 4096, 1700000000000);
        row.IsSettledAt(stamp, "/_webdav/MacCoss/QC/@files/run1.raw")
            .ShouldBeTrue("an unchanged file verified before the update must not be sent again");
    }

    [Fact]
    public async Task Every_row_survives_the_rebuild()
    {
        WriteLegacyLedger(
            (@"D:\Data\a.raw", "/_webdav/p/@files/a.raw", (int)TransferState.Verified),
            (@"D:\Data\b.raw", "/_webdav/p/@files/b.raw", (int)TransferState.Failed),
            (@"D:\Data\c.raw", "/_webdav/p/@files/c.raw", (int)TransferState.Conflict));

        await using var store = new SqliteStateStore(LedgerPath);

        var counts = await store.CountByStateAsync();

        counts[TransferState.Verified].ShouldBe(1);
        counts[TransferState.Failed].ShouldBe(1);
        counts[TransferState.Conflict].ShouldBe(1);
    }

    [Fact]
    public async Task One_file_can_now_be_recorded_at_two_destinations()
    {
        // The behavior the migration exists for: two configurations watching one folder and
        // sending it to different projects. Keyed by path alone the second save overwrote the
        // first, and each configuration then re-uploaded the file on every sweep, for ever.
        WriteLegacyLedger(
            (@"D:\Data\run.raw", "/_webdav/ProjectA/@files/run.raw", (int)TransferState.Verified));

        await using var store = new SqliteStateStore(LedgerPath);

        var stamp = new LocalFileStamp(@"D:\Data\run.raw", 4096, 1700000000000);
        await store.SaveAsync(UploadRecord.ForNewFile(stamp, "/_webdav/ProjectB/@files/run.raw"));

        var a = await store.GetAsync(
            new LedgerKey(@"D:\Data\run.raw", "/_webdav/ProjectA/@files/run.raw"));
        var b = await store.GetAsync(
            new LedgerKey(@"D:\Data\run.raw", "/_webdav/ProjectB/@files/run.raw"));

        a.ShouldNotBeNull("the first configuration's row must survive the second's save");
        a.State.ShouldBe(TransferState.Verified);
        b.ShouldNotBeNull();
    }

    [Fact]
    public async Task Migrating_twice_is_harmless()
    {
        // Guarded on the table's shape rather than the version stamp, because rollback means a
        // stamp can be ahead of what it describes. Opening repeatedly must not rebuild again.
        WriteLegacyLedger(
            (@"D:\Data\run.raw", "/_webdav/p/@files/run.raw", (int)TransferState.Verified));

        await using (var first = new SqliteStateStore(LedgerPath))
        {
            (await first.CountByStateAsync())[TransferState.Verified].ShouldBe(1);
        }

        SqliteConnection.ClearAllPools();

        await using var second = new SqliteStateStore(LedgerPath);
        (await second.CountByStateAsync())[TransferState.Verified].ShouldBe(1);
    }

    [Fact]
    public async Task The_hash_cache_is_untouched_by_the_rebuild()
    {
        // A separate table, and easy to drop by accident when the one beside it is recreated.
        // Losing it costs a re-hash of every file rather than a re-upload, which is cheaper and
        // still not free on an instrument.
        WriteLegacyLedger(
            (@"D:\Data\run.raw", "/_webdav/p/@files/run.raw", (int)TransferState.Verified));

        var stamp = new LocalFileStamp(@"D:\Data\run.raw", 4096, 1700000000000);

        await using (var store = new SqliteStateStore(LedgerPath))
        {
            await store.SaveCachedHashesAsync(
                stamp, new Core.Hashing.ContentHashes("d41d8cd98f00b204e9800998ecf8427e", null));
        }

        SqliteConnection.ClearAllPools();

        await using var reopened = new SqliteStateStore(LedgerPath);
        (await reopened.GetCachedHashesAsync(stamp)).ShouldNotBeNull();
    }

    [Fact]
    public async Task A_rebuild_that_dies_part_way_leaves_the_ledger_as_it_was()
    {
        // Crash-safety, forced rather than waited for. A half-built table left by an attempt that
        // never finished is exactly what a crash between CREATE and RENAME leaves behind, so
        // planting one and opening the ledger exercises the same recovery.
        //
        // What must be true afterwards is the point: the rows are all there, and they are still
        // verified. A migration that loses this costs every instrument its entire upload history.
        WriteLegacyLedger(
            (@"D:\Data\run1.raw", "/_webdav/p/@files/run1.raw", (int)TransferState.Verified),
            (@"D:\Data\run2.raw", "/_webdav/p/@files/run2.raw", (int)TransferState.Verified));

        using (var planted = new SqliteConnection($"Data Source={LedgerPath}"))
        {
            planted.Open();
            using var command = planted.CreateCommand();
            command.CommandText = "CREATE TABLE uploads_rekeyed (local_path TEXT);";
            command.ExecuteNonQuery();
        }

        SqliteConnection.ClearAllPools();

        await using var store = new SqliteStateStore(LedgerPath);

        var counts = await store.CountByStateAsync();
        counts[TransferState.Verified].ShouldBe(2, "no row may be lost to a retried migration");

        var row = await store.GetAsync(
            new LedgerKey(@"D:\Data\run1.raw", "/_webdav/p/@files/run1.raw"));

        row.ShouldNotBeNull();
        row.VerifyMethod.ShouldBe(VerifyMethod.ServerMd5);
    }

    public void Dispose()
    {
        SqliteConnection.ClearAllPools();

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle the pool has not released yet. The temp directory is not worth failing a
            // run over.
        }
    }
}
